default: &default
  flood_minutes: 5
  flood_unrestrict: 10
  flood_count: 5
  
test:
  <<: *default

development:
  flood_minutes: 5
  flood_unrestrict: 10
  flood_count: 1000

production:
  <<: *default
